export const GET_LATEST_STATS = "GET_LATEST_STATS";
export const GET_COUNTRY_STATS = "GET_COUNTRY_STATS";
export const SORT_GLOBAL_STATS = "SORT_GLOBAL_STATS";
export const CALC_STATS_DIFF = "CALC_STATS_DIFF";

export const SET_LATEST_DATE = "SET_LATEST_DATE";
export const SET_LOADING = "SET_LOADING";
