export const GET_LATEST_STATS = "GET_LATEST_STATS";
export const GET_COUNTRY_STATS = "GET_COUNTRY_STATS";
export const SORT_GLOBAL_STATS = "SORT_GLOBAL_STATS";
export const SORT_COUNTRY_STATS = "SORT_COUNTRY_STATS";

export const SET_LOADING = "SET_LOADING";
